version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    network_mode: host
    environment:
      ES: 'Europe/Madrid'
      ADMIN_EMAIL: '${EMAIL}'
      REV_SERVER: 'true'
      REV_SERVER_DOMAIN: '0.0.0.0' # Replace the IP 
      REV_SERVER_TARGET: '0.0.0.0' # Replace the IP 
      REV_SERVER_CIDR: '0.0.0.0/24' # Replace the IP 
      ServerIP: '${YOUR_IP}'
      WEB_PORT: 80
      VIRTUAL_HOST: 'pi.hole'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
